# Generated by Django 2.2 on 2021-10-30 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jobentry',
            managers=[
            ],
        ),
    ]
