# Generated by Django 2.2 on 2021-10-30 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntApp', '0002_auto_20211030_0248'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobEntry',
            new_name='Job',
        ),
    ]
