# Generated by Django 2.2 on 2021-10-30 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobHuntApp', '0003_auto_20211030_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='company_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobHuntApp.User'),
        ),
        migrations.AlterField(
            model_name='job',
            name='position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
